version: '2'

services:
  ssh-mitm-legancy: 
    build:
      context: .
      dockerfile: Dockerfile.amd64
    image: hackinglab/alpine-ssh-mitm-legacy:amd64-3.2.0
    environment:
    - AUTHOR=e1
    - HL_USER_USERNAME=hacker
    - HL_USER_PASSWORD=compass
    ports:
      - "4444:4444"
      - "22:22"
